// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: market/v1/market.proto

package marketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingStatus int32

const (
	ListingStatus_LISTING_STATUS_UNSPECIFIED ListingStatus = 0
	ListingStatus_LISTING_STATUS_ACTIVE      ListingStatus = 1
	ListingStatus_LISTING_STATUS_EXPIRED     ListingStatus = 2
	ListingStatus_LISTING_STATUS_SOLD        ListingStatus = 3
	ListingStatus_LISTING_STATUS_CANCELLED   ListingStatus = 4
)

// Enum value maps for ListingStatus.
var (
	ListingStatus_name = map[int32]string{
		0: "LISTING_STATUS_UNSPECIFIED",
		1: "LISTING_STATUS_ACTIVE",
		2: "LISTING_STATUS_EXPIRED",
		3: "LISTING_STATUS_SOLD",
		4: "LISTING_STATUS_CANCELLED",
	}
	ListingStatus_value = map[string]int32{
		"LISTING_STATUS_UNSPECIFIED": 0,
		"LISTING_STATUS_ACTIVE":      1,
		"LISTING_STATUS_EXPIRED":     2,
		"LISTING_STATUS_SOLD":        3,
		"LISTING_STATUS_CANCELLED":   4,
	}
)

func (x ListingStatus) Enum() *ListingStatus {
	p := new(ListingStatus)
	*p = x
	return p
}

func (x ListingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_market_v1_market_proto_enumTypes[0].Descriptor()
}

func (ListingStatus) Type() protoreflect.EnumType {
	return &file_market_v1_market_proto_enumTypes[0]
}

func (x ListingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListingStatus.Descriptor instead.
func (ListingStatus) EnumDescriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{0}
}

type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerUserId  string                 `protobuf:"bytes,1,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	UserCardId    string                 `protobuf:"bytes,2,opt,name=user_card_id,json=userCardId,proto3" json:"user_card_id,omitempty"`
	StartPrice    int64                  `protobuf:"varint,3,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	BuyNowPrice   int64                  `protobuf:"varint,4,opt,name=buy_now_price,json=buyNowPrice,proto3" json:"buy_now_price,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,5,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListingRequest) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *CreateListingRequest) GetUserCardId() string {
	if x != nil {
		return x.UserCardId
	}
	return ""
}

func (x *CreateListingRequest) GetStartPrice() int64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *CreateListingRequest) GetBuyNowPrice() int64 {
	if x != nil {
		return x.BuyNowPrice
	}
	return 0
}

func (x *CreateListingRequest) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type CreateListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingResponse) Reset() {
	*x = CreateListingResponse{}
	mi := &file_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingResponse) ProtoMessage() {}

func (x *CreateListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingResponse.ProtoReflect.Descriptor instead.
func (*CreateListingResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *CreateListingResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	BidderUserId  string                 `protobuf:"bytes,2,opt,name=bidder_user_id,json=bidderUserId,proto3" json:"bidder_user_id,omitempty"`
	BidAmount     int64                  `protobuf:"varint,3,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceBidRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *PlaceBidRequest) GetBidderUserId() string {
	if x != nil {
		return x.BidderUserId
	}
	return ""
}

func (x *PlaceBidRequest) GetBidAmount() int64 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

type PlaceBidResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BestBid          int64                  `protobuf:"varint,1,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestBidderUserId string                 `protobuf:"bytes,2,opt,name=best_bidder_user_id,json=bestBidderUserId,proto3" json:"best_bidder_user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceBidResponse) GetBestBid() int64 {
	if x != nil {
		return x.BestBid
	}
	return 0
}

func (x *PlaceBidResponse) GetBestBidderUserId() string {
	if x != nil {
		return x.BestBidderUserId
	}
	return ""
}

type BuyNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyNowRequest) Reset() {
	*x = BuyNowRequest{}
	mi := &file_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyNowRequest) ProtoMessage() {}

func (x *BuyNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyNowRequest.ProtoReflect.Descriptor instead.
func (*BuyNowRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *BuyNowRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *BuyNowRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

type BuyNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchased     bool                   `protobuf:"varint,1,opt,name=purchased,proto3" json:"purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyNowResponse) Reset() {
	*x = BuyNowResponse{}
	mi := &file_market_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyNowResponse) ProtoMessage() {}

func (x *BuyNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyNowResponse.ProtoReflect.Descriptor instead.
func (*BuyNowResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *BuyNowResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_market_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{6}
}

func (x *GetListingRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

type GetListingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ListingId        string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	SellerUserId     string                 `protobuf:"bytes,2,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	UserCardId       string                 `protobuf:"bytes,3,opt,name=user_card_id,json=userCardId,proto3" json:"user_card_id,omitempty"`
	StartPrice       int64                  `protobuf:"varint,4,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	BuyNowPrice      int64                  `protobuf:"varint,5,opt,name=buy_now_price,json=buyNowPrice,proto3" json:"buy_now_price,omitempty"`
	BestBid          int64                  `protobuf:"varint,6,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestBidderUserId string                 `protobuf:"bytes,7,opt,name=best_bidder_user_id,json=bestBidderUserId,proto3" json:"best_bidder_user_id,omitempty"`
	ExpiresAtUnix    int64                  `protobuf:"varint,8,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Status           ListingStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=market.v1.ListingStatus" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetListingResponse) Reset() {
	*x = GetListingResponse{}
	mi := &file_market_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingResponse) ProtoMessage() {}

func (x *GetListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingResponse.ProtoReflect.Descriptor instead.
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{7}
}

func (x *GetListingResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *GetListingResponse) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *GetListingResponse) GetUserCardId() string {
	if x != nil {
		return x.UserCardId
	}
	return ""
}

func (x *GetListingResponse) GetStartPrice() int64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *GetListingResponse) GetBuyNowPrice() int64 {
	if x != nil {
		return x.BuyNowPrice
	}
	return 0
}

func (x *GetListingResponse) GetBestBid() int64 {
	if x != nil {
		return x.BestBid
	}
	return 0
}

func (x *GetListingResponse) GetBestBidderUserId() string {
	if x != nil {
		return x.BestBidderUserId
	}
	return ""
}

func (x *GetListingResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *GetListingResponse) GetStatus() ListingStatus {
	if x != nil {
		return x.Status
	}
	return ListingStatus_LISTING_STATUS_UNSPECIFIED
}

var File_market_v1_market_proto protoreflect.FileDescriptor

const file_market_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x16market/v1/market.proto\x12\tmarket.v1\"\xcb\x01\n" +
	"\x14CreateListingRequest\x12$\n" +
	"\x0eseller_user_id\x18\x01 \x01(\tR\fsellerUserId\x12 \n" +
	"\fuser_card_id\x18\x02 \x01(\tR\n" +
	"userCardId\x12\x1f\n" +
	"\vstart_price\x18\x03 \x01(\x03R\n" +
	"startPrice\x12\"\n" +
	"\rbuy_now_price\x18\x04 \x01(\x03R\vbuyNowPrice\x12&\n" +
	"\x0fexpires_at_unix\x18\x05 \x01(\x03R\rexpiresAtUnix\"6\n" +
	"\x15CreateListingResponse\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\"u\n" +
	"\x0fPlaceBidRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12$\n" +
	"\x0ebidder_user_id\x18\x02 \x01(\tR\fbidderUserId\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x03 \x01(\x03R\tbidAmount\"\\\n" +
	"\x10PlaceBidResponse\x12\x19\n" +
	"\bbest_bid\x18\x01 \x01(\x03R\abestBid\x12-\n" +
	"\x13best_bidder_user_id\x18\x02 \x01(\tR\x10bestBidderUserId\"R\n" +
	"\rBuyNowRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\".\n" +
	"\x0eBuyNowResponse\x12\x1c\n" +
	"\tpurchased\x18\x01 \x01(\bR\tpurchased\"2\n" +
	"\x11GetListingRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\"\xe4\x02\n" +
	"\x12GetListingResponse\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12$\n" +
	"\x0eseller_user_id\x18\x02 \x01(\tR\fsellerUserId\x12 \n" +
	"\fuser_card_id\x18\x03 \x01(\tR\n" +
	"userCardId\x12\x1f\n" +
	"\vstart_price\x18\x04 \x01(\x03R\n" +
	"startPrice\x12\"\n" +
	"\rbuy_now_price\x18\x05 \x01(\x03R\vbuyNowPrice\x12\x19\n" +
	"\bbest_bid\x18\x06 \x01(\x03R\abestBid\x12-\n" +
	"\x13best_bidder_user_id\x18\a \x01(\tR\x10bestBidderUserId\x12&\n" +
	"\x0fexpires_at_unix\x18\b \x01(\x03R\rexpiresAtUnix\x120\n" +
	"\x06status\x18\t \x01(\x0e2\x18.market.v1.ListingStatusR\x06status*\x9d\x01\n" +
	"\rListingStatus\x12\x1e\n" +
	"\x1aLISTING_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LISTING_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16LISTING_STATUS_EXPIRED\x10\x02\x12\x17\n" +
	"\x13LISTING_STATUS_SOLD\x10\x03\x12\x1c\n" +
	"\x18LISTING_STATUS_CANCELLED\x10\x042\xb2\x02\n" +
	"\rMarketService\x12R\n" +
	"\rCreateListing\x12\x1f.market.v1.CreateListingRequest\x1a .market.v1.CreateListingResponse\x12C\n" +
	"\bPlaceBid\x12\x1a.market.v1.PlaceBidRequest\x1a\x1b.market.v1.PlaceBidResponse\x12=\n" +
	"\x06BuyNow\x12\x18.market.v1.BuyNowRequest\x1a\x19.market.v1.BuyNowResponse\x12I\n" +
	"\n" +
	"GetListing\x12\x1c.market.v1.GetListingRequest\x1a\x1d.market.v1.GetListingResponseB\x89\x01\n" +
	"\rcom.market.v1B\vMarketProtoP\x01Z&UltimateTeamX/proto/market/v1;marketv1\xa2\x02\x03MXX\xaa\x02\tMarket.V1\xca\x02\tMarket\\V1\xe2\x02\x15Market\\V1\\GPBMetadata\xea\x02\n" +
	"Market::V1b\x06proto3"

var (
	file_market_v1_market_proto_rawDescOnce sync.Once
	file_market_v1_market_proto_rawDescData []byte
)

func file_market_v1_market_proto_rawDescGZIP() []byte {
	file_market_v1_market_proto_rawDescOnce.Do(func() {
		file_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)))
	})
	return file_market_v1_market_proto_rawDescData
}

var file_market_v1_market_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_market_v1_market_proto_goTypes = []any{
	(ListingStatus)(0),            // 0: market.v1.ListingStatus
	(*CreateListingRequest)(nil),  // 1: market.v1.CreateListingRequest
	(*CreateListingResponse)(nil), // 2: market.v1.CreateListingResponse
	(*PlaceBidRequest)(nil),       // 3: market.v1.PlaceBidRequest
	(*PlaceBidResponse)(nil),      // 4: market.v1.PlaceBidResponse
	(*BuyNowRequest)(nil),         // 5: market.v1.BuyNowRequest
	(*BuyNowResponse)(nil),        // 6: market.v1.BuyNowResponse
	(*GetListingRequest)(nil),     // 7: market.v1.GetListingRequest
	(*GetListingResponse)(nil),    // 8: market.v1.GetListingResponse
}
var file_market_v1_market_proto_depIdxs = []int32{
	0, // 0: market.v1.GetListingResponse.status:type_name -> market.v1.ListingStatus
	1, // 1: market.v1.MarketService.CreateListing:input_type -> market.v1.CreateListingRequest
	3, // 2: market.v1.MarketService.PlaceBid:input_type -> market.v1.PlaceBidRequest
	5, // 3: market.v1.MarketService.BuyNow:input_type -> market.v1.BuyNowRequest
	7, // 4: market.v1.MarketService.GetListing:input_type -> market.v1.GetListingRequest
	2, // 5: market.v1.MarketService.CreateListing:output_type -> market.v1.CreateListingResponse
	4, // 6: market.v1.MarketService.PlaceBid:output_type -> market.v1.PlaceBidResponse
	6, // 7: market.v1.MarketService.BuyNow:output_type -> market.v1.BuyNowResponse
	8, // 8: market.v1.MarketService.GetListing:output_type -> market.v1.GetListingResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_v1_market_proto_init() }
func file_market_v1_market_proto_init() {
	if File_market_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_v1_market_proto_goTypes,
		DependencyIndexes: file_market_v1_market_proto_depIdxs,
		EnumInfos:         file_market_v1_market_proto_enumTypes,
		MessageInfos:      file_market_v1_market_proto_msgTypes,
	}.Build()
	File_market_v1_market_proto = out.File
	file_market_v1_market_proto_goTypes = nil
	file_market_v1_market_proto_depIdxs = nil
}
