// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: club/v1/club.proto

package clubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClubService_GetClub_FullMethodName           = "/club.v1.ClubService/GetClub"
	ClubService_GetMyClub_FullMethodName         = "/club.v1.ClubService/GetMyClub"
	ClubService_LockCard_FullMethodName          = "/club.v1.ClubService/LockCard"
	ClubService_ReleaseCardLock_FullMethodName   = "/club.v1.ClubService/ReleaseCardLock"
	ClubService_CreateCreditHold_FullMethodName  = "/club.v1.ClubService/CreateCreditHold"
	ClubService_ReleaseCreditHold_FullMethodName = "/club.v1.ClubService/ReleaseCreditHold"
	ClubService_SettleTrade_FullMethodName       = "/club.v1.ClubService/SettleTrade"
)

// ClubServiceClient is the client API for ClubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClubServiceClient interface {
	GetClub(ctx context.Context, in *GetClubRequest, opts ...grpc.CallOption) (*GetClubResponse, error)
	GetMyClub(ctx context.Context, in *GetMyClubRequest, opts ...grpc.CallOption) (*GetMyClubResponse, error)
	LockCard(ctx context.Context, in *LockCardRequest, opts ...grpc.CallOption) (*LockCardResponse, error)
	ReleaseCardLock(ctx context.Context, in *ReleaseCardLockRequest, opts ...grpc.CallOption) (*ReleaseCardLockResponse, error)
	CreateCreditHold(ctx context.Context, in *CreateCreditHoldRequest, opts ...grpc.CallOption) (*CreateCreditHoldResponse, error)
	ReleaseCreditHold(ctx context.Context, in *ReleaseCreditHoldRequest, opts ...grpc.CallOption) (*ReleaseCreditHoldResponse, error)
	SettleTrade(ctx context.Context, in *SettleTradeRequest, opts ...grpc.CallOption) (*SettleTradeResponse, error)
}

type clubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClubServiceClient(cc grpc.ClientConnInterface) ClubServiceClient {
	return &clubServiceClient{cc}
}

func (c *clubServiceClient) GetClub(ctx context.Context, in *GetClubRequest, opts ...grpc.CallOption) (*GetClubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClubResponse)
	err := c.cc.Invoke(ctx, ClubService_GetClub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) GetMyClub(ctx context.Context, in *GetMyClubRequest, opts ...grpc.CallOption) (*GetMyClubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyClubResponse)
	err := c.cc.Invoke(ctx, ClubService_GetMyClub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) LockCard(ctx context.Context, in *LockCardRequest, opts ...grpc.CallOption) (*LockCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockCardResponse)
	err := c.cc.Invoke(ctx, ClubService_LockCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) ReleaseCardLock(ctx context.Context, in *ReleaseCardLockRequest, opts ...grpc.CallOption) (*ReleaseCardLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCardLockResponse)
	err := c.cc.Invoke(ctx, ClubService_ReleaseCardLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) CreateCreditHold(ctx context.Context, in *CreateCreditHoldRequest, opts ...grpc.CallOption) (*CreateCreditHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCreditHoldResponse)
	err := c.cc.Invoke(ctx, ClubService_CreateCreditHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) ReleaseCreditHold(ctx context.Context, in *ReleaseCreditHoldRequest, opts ...grpc.CallOption) (*ReleaseCreditHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCreditHoldResponse)
	err := c.cc.Invoke(ctx, ClubService_ReleaseCreditHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) SettleTrade(ctx context.Context, in *SettleTradeRequest, opts ...grpc.CallOption) (*SettleTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleTradeResponse)
	err := c.cc.Invoke(ctx, ClubService_SettleTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClubServiceServer is the server API for ClubService service.
// All implementations must embed UnimplementedClubServiceServer
// for forward compatibility.
type ClubServiceServer interface {
	GetClub(context.Context, *GetClubRequest) (*GetClubResponse, error)
	GetMyClub(context.Context, *GetMyClubRequest) (*GetMyClubResponse, error)
	LockCard(context.Context, *LockCardRequest) (*LockCardResponse, error)
	ReleaseCardLock(context.Context, *ReleaseCardLockRequest) (*ReleaseCardLockResponse, error)
	CreateCreditHold(context.Context, *CreateCreditHoldRequest) (*CreateCreditHoldResponse, error)
	ReleaseCreditHold(context.Context, *ReleaseCreditHoldRequest) (*ReleaseCreditHoldResponse, error)
	SettleTrade(context.Context, *SettleTradeRequest) (*SettleTradeResponse, error)
	mustEmbedUnimplementedClubServiceServer()
}

// UnimplementedClubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClubServiceServer struct{}

func (UnimplementedClubServiceServer) GetClub(context.Context, *GetClubRequest) (*GetClubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClub not implemented")
}
func (UnimplementedClubServiceServer) GetMyClub(context.Context, *GetMyClubRequest) (*GetMyClubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyClub not implemented")
}
func (UnimplementedClubServiceServer) LockCard(context.Context, *LockCardRequest) (*LockCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockCard not implemented")
}
func (UnimplementedClubServiceServer) ReleaseCardLock(context.Context, *ReleaseCardLockRequest) (*ReleaseCardLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseCardLock not implemented")
}
func (UnimplementedClubServiceServer) CreateCreditHold(context.Context, *CreateCreditHoldRequest) (*CreateCreditHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCreditHold not implemented")
}
func (UnimplementedClubServiceServer) ReleaseCreditHold(context.Context, *ReleaseCreditHoldRequest) (*ReleaseCreditHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseCreditHold not implemented")
}
func (UnimplementedClubServiceServer) SettleTrade(context.Context, *SettleTradeRequest) (*SettleTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleTrade not implemented")
}
func (UnimplementedClubServiceServer) mustEmbedUnimplementedClubServiceServer() {}
func (UnimplementedClubServiceServer) testEmbeddedByValue()                     {}

// UnsafeClubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClubServiceServer will
// result in compilation errors.
type UnsafeClubServiceServer interface {
	mustEmbedUnimplementedClubServiceServer()
}

func RegisterClubServiceServer(s grpc.ServiceRegistrar, srv ClubServiceServer) {
	// If the following call panics, it indicates UnimplementedClubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClubService_ServiceDesc, srv)
}

func _ClubService_GetClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).GetClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_GetClub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).GetClub(ctx, req.(*GetClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_GetMyClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).GetMyClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_GetMyClub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).GetMyClub(ctx, req.(*GetMyClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_LockCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).LockCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_LockCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).LockCard(ctx, req.(*LockCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_ReleaseCardLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCardLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).ReleaseCardLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_ReleaseCardLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).ReleaseCardLock(ctx, req.(*ReleaseCardLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_CreateCreditHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCreditHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).CreateCreditHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_CreateCreditHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).CreateCreditHold(ctx, req.(*CreateCreditHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_ReleaseCreditHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCreditHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).ReleaseCreditHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_ReleaseCreditHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).ReleaseCreditHold(ctx, req.(*ReleaseCreditHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_SettleTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).SettleTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_SettleTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).SettleTrade(ctx, req.(*SettleTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClubService_ServiceDesc is the grpc.ServiceDesc for ClubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "club.v1.ClubService",
	HandlerType: (*ClubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClub",
			Handler:    _ClubService_GetClub_Handler,
		},
		{
			MethodName: "GetMyClub",
			Handler:    _ClubService_GetMyClub_Handler,
		},
		{
			MethodName: "LockCard",
			Handler:    _ClubService_LockCard_Handler,
		},
		{
			MethodName: "ReleaseCardLock",
			Handler:    _ClubService_ReleaseCardLock_Handler,
		},
		{
			MethodName: "CreateCreditHold",
			Handler:    _ClubService_CreateCreditHold_Handler,
		},
		{
			MethodName: "ReleaseCreditHold",
			Handler:    _ClubService_ReleaseCreditHold_Handler,
		},
		{
			MethodName: "SettleTrade",
			Handler:    _ClubService_SettleTrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "club/v1/club.proto",
}
