// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: club/v1/club.proto

package clubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClubRequest) Reset() {
	*x = GetClubRequest{}
	mi := &file_club_v1_club_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClubRequest) ProtoMessage() {}

func (x *GetClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClubRequest.ProtoReflect.Descriptor instead.
func (*GetClubRequest) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{0}
}

func (x *GetClubRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetClubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credits       int64                  `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClubResponse) Reset() {
	*x = GetClubResponse{}
	mi := &file_club_v1_club_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClubResponse) ProtoMessage() {}

func (x *GetClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClubResponse.ProtoReflect.Descriptor instead.
func (*GetClubResponse) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{1}
}

func (x *GetClubResponse) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

type GetMyClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyClubRequest) Reset() {
	*x = GetMyClubRequest{}
	mi := &file_club_v1_club_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyClubRequest) ProtoMessage() {}

func (x *GetMyClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyClubRequest.ProtoReflect.Descriptor instead.
func (*GetMyClubRequest) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{2}
}

type GetMyClubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credits       int64                  `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyClubResponse) Reset() {
	*x = GetMyClubResponse{}
	mi := &file_club_v1_club_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyClubResponse) ProtoMessage() {}

func (x *GetMyClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyClubResponse.ProtoReflect.Descriptor instead.
func (*GetMyClubResponse) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyClubResponse) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *GetMyClubResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Locked        bool                   `protobuf:"varint,3,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_club_v1_club_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Card) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

type LockCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCardId    string                 `protobuf:"bytes,2,opt,name=user_card_id,json=userCardId,proto3" json:"user_card_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockCardRequest) Reset() {
	*x = LockCardRequest{}
	mi := &file_club_v1_club_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockCardRequest) ProtoMessage() {}

func (x *LockCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockCardRequest.ProtoReflect.Descriptor instead.
func (*LockCardRequest) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{5}
}

func (x *LockCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LockCardRequest) GetUserCardId() string {
	if x != nil {
		return x.UserCardId
	}
	return ""
}

func (x *LockCardRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LockCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockCardResponse) Reset() {
	*x = LockCardResponse{}
	mi := &file_club_v1_club_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockCardResponse) ProtoMessage() {}

func (x *LockCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockCardResponse.ProtoReflect.Descriptor instead.
func (*LockCardResponse) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{6}
}

func (x *LockCardResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type ReleaseCardLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCardLockRequest) Reset() {
	*x = ReleaseCardLockRequest{}
	mi := &file_club_v1_club_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCardLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCardLockRequest) ProtoMessage() {}

func (x *ReleaseCardLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCardLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCardLockRequest) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseCardLockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type ReleaseCardLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCardLockResponse) Reset() {
	*x = ReleaseCardLockResponse{}
	mi := &file_club_v1_club_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCardLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCardLockResponse) ProtoMessage() {}

func (x *ReleaseCardLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCardLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseCardLockResponse) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseCardLockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type CreateCreditHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCreditHoldRequest) Reset() {
	*x = CreateCreditHoldRequest{}
	mi := &file_club_v1_club_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCreditHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCreditHoldRequest) ProtoMessage() {}

func (x *CreateCreditHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCreditHoldRequest.ProtoReflect.Descriptor instead.
func (*CreateCreditHoldRequest) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCreditHoldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCreditHoldRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateCreditHoldRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateCreditHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCreditHoldResponse) Reset() {
	*x = CreateCreditHoldResponse{}
	mi := &file_club_v1_club_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCreditHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCreditHoldResponse) ProtoMessage() {}

func (x *CreateCreditHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCreditHoldResponse.ProtoReflect.Descriptor instead.
func (*CreateCreditHoldResponse) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCreditHoldResponse) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

type ReleaseCreditHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCreditHoldRequest) Reset() {
	*x = ReleaseCreditHoldRequest{}
	mi := &file_club_v1_club_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCreditHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCreditHoldRequest) ProtoMessage() {}

func (x *ReleaseCreditHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCreditHoldRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCreditHoldRequest) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseCreditHoldRequest) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

type ReleaseCreditHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCreditHoldResponse) Reset() {
	*x = ReleaseCreditHoldResponse{}
	mi := &file_club_v1_club_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCreditHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCreditHoldResponse) ProtoMessage() {}

func (x *ReleaseCreditHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCreditHoldResponse.ProtoReflect.Descriptor instead.
func (*ReleaseCreditHoldResponse) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseCreditHoldResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type SettleTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerUserId  string                 `protobuf:"bytes,1,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,2,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	UserCardId    string                 `protobuf:"bytes,3,opt,name=user_card_id,json=userCardId,proto3" json:"user_card_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleTradeRequest) Reset() {
	*x = SettleTradeRequest{}
	mi := &file_club_v1_club_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleTradeRequest) ProtoMessage() {}

func (x *SettleTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleTradeRequest.ProtoReflect.Descriptor instead.
func (*SettleTradeRequest) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{13}
}

func (x *SettleTradeRequest) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *SettleTradeRequest) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *SettleTradeRequest) GetUserCardId() string {
	if x != nil {
		return x.UserCardId
	}
	return ""
}

func (x *SettleTradeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SettleTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settled       bool                   `protobuf:"varint,1,opt,name=settled,proto3" json:"settled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleTradeResponse) Reset() {
	*x = SettleTradeResponse{}
	mi := &file_club_v1_club_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleTradeResponse) ProtoMessage() {}

func (x *SettleTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_v1_club_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleTradeResponse.ProtoReflect.Descriptor instead.
func (*SettleTradeResponse) Descriptor() ([]byte, []int) {
	return file_club_v1_club_proto_rawDescGZIP(), []int{14}
}

func (x *SettleTradeResponse) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

var File_club_v1_club_proto protoreflect.FileDescriptor

const file_club_v1_club_proto_rawDesc = "" +
	"\n" +
	"\x12club/v1/club.proto\x12\aclub.v1\")\n" +
	"\x0eGetClubRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"+\n" +
	"\x0fGetClubResponse\x12\x18\n" +
	"\acredits\x18\x01 \x01(\x03R\acredits\"\x12\n" +
	"\x10GetMyClubRequest\"R\n" +
	"\x11GetMyClubResponse\x12\x18\n" +
	"\acredits\x18\x01 \x01(\x03R\acredits\x12#\n" +
	"\x05cards\x18\x02 \x03(\v2\r.club.v1.CardR\x05cards\"K\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06locked\x18\x03 \x01(\bR\x06locked\"d\n" +
	"\x0fLockCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fuser_card_id\x18\x02 \x01(\tR\n" +
	"userCardId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"+\n" +
	"\x10LockCardResponse\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"1\n" +
	"\x16ReleaseCardLockRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"5\n" +
	"\x17ReleaseCardLockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"b\n" +
	"\x17CreateCreditHoldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"3\n" +
	"\x18CreateCreditHoldResponse\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\"3\n" +
	"\x18ReleaseCreditHoldRequest\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\"7\n" +
	"\x19ReleaseCreditHoldResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"\x98\x01\n" +
	"\x12SettleTradeRequest\x12$\n" +
	"\x0eseller_user_id\x18\x01 \x01(\tR\fsellerUserId\x12\"\n" +
	"\rbuyer_user_id\x18\x02 \x01(\tR\vbuyerUserId\x12 \n" +
	"\fuser_card_id\x18\x03 \x01(\tR\n" +
	"userCardId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"/\n" +
	"\x13SettleTradeResponse\x12\x18\n" +
	"\asettled\x18\x01 \x01(\bR\asettled2\xa5\x04\n" +
	"\vClubService\x12<\n" +
	"\aGetClub\x12\x17.club.v1.GetClubRequest\x1a\x18.club.v1.GetClubResponse\x12B\n" +
	"\tGetMyClub\x12\x19.club.v1.GetMyClubRequest\x1a\x1a.club.v1.GetMyClubResponse\x12?\n" +
	"\bLockCard\x12\x18.club.v1.LockCardRequest\x1a\x19.club.v1.LockCardResponse\x12T\n" +
	"\x0fReleaseCardLock\x12\x1f.club.v1.ReleaseCardLockRequest\x1a .club.v1.ReleaseCardLockResponse\x12W\n" +
	"\x10CreateCreditHold\x12 .club.v1.CreateCreditHoldRequest\x1a!.club.v1.CreateCreditHoldResponse\x12Z\n" +
	"\x11ReleaseCreditHold\x12!.club.v1.ReleaseCreditHoldRequest\x1a\".club.v1.ReleaseCreditHoldResponse\x12H\n" +
	"\vSettleTrade\x12\x1b.club.v1.SettleTradeRequest\x1a\x1c.club.v1.SettleTradeResponseBy\n" +
	"\vcom.club.v1B\tClubProtoP\x01Z\"UltimateTeamX/proto/club/v1;clubv1\xa2\x02\x03CXX\xaa\x02\aClub.V1\xca\x02\aClub\\V1\xe2\x02\x13Club\\V1\\GPBMetadata\xea\x02\bClub::V1b\x06proto3"

var (
	file_club_v1_club_proto_rawDescOnce sync.Once
	file_club_v1_club_proto_rawDescData []byte
)

func file_club_v1_club_proto_rawDescGZIP() []byte {
	file_club_v1_club_proto_rawDescOnce.Do(func() {
		file_club_v1_club_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_club_v1_club_proto_rawDesc), len(file_club_v1_club_proto_rawDesc)))
	})
	return file_club_v1_club_proto_rawDescData
}

var file_club_v1_club_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_club_v1_club_proto_goTypes = []any{
	(*GetClubRequest)(nil),            // 0: club.v1.GetClubRequest
	(*GetClubResponse)(nil),           // 1: club.v1.GetClubResponse
	(*GetMyClubRequest)(nil),          // 2: club.v1.GetMyClubRequest
	(*GetMyClubResponse)(nil),         // 3: club.v1.GetMyClubResponse
	(*Card)(nil),                      // 4: club.v1.Card
	(*LockCardRequest)(nil),           // 5: club.v1.LockCardRequest
	(*LockCardResponse)(nil),          // 6: club.v1.LockCardResponse
	(*ReleaseCardLockRequest)(nil),    // 7: club.v1.ReleaseCardLockRequest
	(*ReleaseCardLockResponse)(nil),   // 8: club.v1.ReleaseCardLockResponse
	(*CreateCreditHoldRequest)(nil),   // 9: club.v1.CreateCreditHoldRequest
	(*CreateCreditHoldResponse)(nil),  // 10: club.v1.CreateCreditHoldResponse
	(*ReleaseCreditHoldRequest)(nil),  // 11: club.v1.ReleaseCreditHoldRequest
	(*ReleaseCreditHoldResponse)(nil), // 12: club.v1.ReleaseCreditHoldResponse
	(*SettleTradeRequest)(nil),        // 13: club.v1.SettleTradeRequest
	(*SettleTradeResponse)(nil),       // 14: club.v1.SettleTradeResponse
}
var file_club_v1_club_proto_depIdxs = []int32{
	4,  // 0: club.v1.GetMyClubResponse.cards:type_name -> club.v1.Card
	0,  // 1: club.v1.ClubService.GetClub:input_type -> club.v1.GetClubRequest
	2,  // 2: club.v1.ClubService.GetMyClub:input_type -> club.v1.GetMyClubRequest
	5,  // 3: club.v1.ClubService.LockCard:input_type -> club.v1.LockCardRequest
	7,  // 4: club.v1.ClubService.ReleaseCardLock:input_type -> club.v1.ReleaseCardLockRequest
	9,  // 5: club.v1.ClubService.CreateCreditHold:input_type -> club.v1.CreateCreditHoldRequest
	11, // 6: club.v1.ClubService.ReleaseCreditHold:input_type -> club.v1.ReleaseCreditHoldRequest
	13, // 7: club.v1.ClubService.SettleTrade:input_type -> club.v1.SettleTradeRequest
	1,  // 8: club.v1.ClubService.GetClub:output_type -> club.v1.GetClubResponse
	3,  // 9: club.v1.ClubService.GetMyClub:output_type -> club.v1.GetMyClubResponse
	6,  // 10: club.v1.ClubService.LockCard:output_type -> club.v1.LockCardResponse
	8,  // 11: club.v1.ClubService.ReleaseCardLock:output_type -> club.v1.ReleaseCardLockResponse
	10, // 12: club.v1.ClubService.CreateCreditHold:output_type -> club.v1.CreateCreditHoldResponse
	12, // 13: club.v1.ClubService.ReleaseCreditHold:output_type -> club.v1.ReleaseCreditHoldResponse
	14, // 14: club.v1.ClubService.SettleTrade:output_type -> club.v1.SettleTradeResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_club_v1_club_proto_init() }
func file_club_v1_club_proto_init() {
	if File_club_v1_club_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_club_v1_club_proto_rawDesc), len(file_club_v1_club_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_club_v1_club_proto_goTypes,
		DependencyIndexes: file_club_v1_club_proto_depIdxs,
		MessageInfos:      file_club_v1_club_proto_msgTypes,
	}.Build()
	File_club_v1_club_proto = out.File
	file_club_v1_club_proto_goTypes = nil
	file_club_v1_club_proto_depIdxs = nil
}
